markdown: redcarpet

baseurl: /deliteful

pygments: true

redcarpet:
  extensions: ['tables']

paginate: 3

defaults:
  -
    scope:
      path: ""
    values:
      layout: "main"
  -
    scope:
      path: "docs"
    values:
      layout: "default"
  -
    scope:
      path: "../_posts"
    values:
      layout: "post"